<h1>Reset Password</h1>

<?php
echo $this->flashMessenger()->renderCurrent();

echo $this->form()->openTag($form);
$passwordElem = $this->form->get('password');
$passwordConfirmElem = $this->form->get('passwordConfirm');
$submitElem = $this->form->get('submit');
?>

<dl class="dl-form">
    <dt><?php echo $this->formLabel($passwordElem) ?></dt>
    <dd><?php echo $this->formElement($passwordElem) ?></dd>

    <dt><?php echo $this->formLabel($passwordConfirmElem) ?></dt>
    <dd><?php echo $this->formElement($passwordConfirmElem) ?></dd>

    <dd>
        <?php echo $this->formElement($submitElem) ?>
    </dd>
</dl>

<?php echo $this->form()->closeTag() ?>
